apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubermatic-dl-deployment
spec:
  selector:
    matchLabels:
      app: kubermatic-dl
  replicas: 2
  template:
    metadata:
      labels:
        app: kubermatic-dl
    spec:
      containers:
      - name: kubermatic-dl
        image: TU_REGISTRO.azurecr.io/kubermatic-dl:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
